### ISSUE TITLE
Colours from the normals calculation have to be estimated

### ISSUE THREAD

**Issue by Renart-fox** [JJponciano/3D-objects-segmentation#1]
Currently the algorithm doesn't take in charge the fact that some points may have to be of the same colour after calculating the normals. e.g a wall in real life isn't totally flat so when you're colouring it some points may not have the correct colour after calcultion.
This has to be fixed so the clustering can be done correctly, as it runs thanks to the colours and if a wall is made of 5 different colours the segmentation will think it is 5 different objects.

**Comment by m0glan** [comment]
The issues has been fixed partially by cloud homogenization.
